version: '3'
services:
  web:
    image: java_springv1
    build: .
    ports:
      - "8091:8091"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped 
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/t1_juiceVRLD/volumes
